name: BiTGApps Build

on:
  workflow_dispatch:

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    if: github.repository_owner == 'BiTGApps'
    runs-on: ubuntu-latest

    steps:
       - name: Initial Setup
         uses: actions/checkout@v2

       - name: Create BiTGApps
         run: |
           rm -rf BiTGApps
           mkdir BiTGApps
           install -d out

       - name: Clone Build Sources
         run: |
           git clone https://github.com/BiTGApps/BiTGApps-Package BiTGApps

       - name: Create Sources
         run: |
           mkdir BiTGApps/sources

       - name: Install Git LFS
         run: |
           wget https://github.com/git-lfs/git-lfs/releases/download/v3.2.0/git-lfs-linux-amd64-v3.2.0.tar.gz
           tar -xz -f git-lfs-linux-amd64-v3.2.0.tar.gz && cd git-lfs-3.2.0 && sudo ./install.sh && cd ..

       - name: Clone Package Sources
         run: |
           git clone https://github.com/BiTGApps/addon-sources BiTGApps/sources/addon-sources
           cd BiTGApps/sources/addon-sources && git lfs install --local && git lfs pull && cd ../..

       - name: Initialize Package Sources
         run: |
           cp -rf BiTGApps/sources/addon-sources/Gearhead BiTGApps/Gearhead
           cp -rf BiTGApps/sources/addon-sources/Markup BiTGApps/Markup
           cp -rf BiTGApps/sources/addon-sources/Velvet BiTGApps/Velvet

       - name: Remove Package Sources
         run: |
           rm -rf BiTGApps/sources

       - name: Build Velvet Package
         run: |
           cd BiTGApps/Velvet
           . envsetup.sh && rm -rf envsetup.sh
           zip -qr9 Velvet-v1.3.zip * && cd ../..
           cp -f BiTGApps/Velvet/Velvet-v1.3.zip out

       - name: Sign Velvet Package
         run: |
           wget https://github.com/BiTGApps/BiTGApps/raw/master/tools/zipsigner/zipsigner.jar
           sudo java -jar zipsigner.jar out/Velvet-v1.3.zip out/Velvet-v1.3-Signed.zip
           rm -rf out/Velvet-v1.3.zip && mv -f out/Velvet-v1.3-Signed.zip out/Velvet-v1.3.zip
           mv -f out/Velvet-v1.3.zip out/Assistant-v1.3.zip

       - name: Build Gearhead Package
         run: |
           cd BiTGApps/Gearhead
           . envsetup.sh && rm -rf envsetup.sh
           zip -qr9 Gearhead-v1.3.zip * && cd ../..
           cp -f BiTGApps/Gearhead/Gearhead-v1.3.zip out

       - name: Sign Gearhead Package
         run: |
           sudo java -jar zipsigner.jar out/Gearhead-v1.3.zip out/Gearhead-v1.3-Signed.zip
           rm -rf out/Gearhead-v1.3.zip && mv -f out/Gearhead-v1.3-Signed.zip out/Gearhead-v1.3.zip
           mv -f out/Gearhead-v1.3.zip out/AndroidAuto-v1.3.zip

       - name: Build Markup Package
         run: |
           cd BiTGApps/Markup
           . envsetup.sh && rm -rf envsetup.sh
           zip -qr9 Markup-v1.3.zip * && cd ../..
           cp -f BiTGApps/Markup/Markup-v1.3.zip out

       - name: Sign Markup Package
         run: |
           sudo java -jar zipsigner.jar out/Markup-v1.3.zip out/Markup-v1.3-Signed.zip
           rm -rf out/Markup-v1.3.zip && mv -f out/Markup-v1.3-Signed.zip out/Markup-v1.3.zip

       - name: Github Release CLI
         run: |
           npm install -g github-release-cli

       - name: Release Signed Package
         env:
           RELEASE: v1.3
         run: |
           github-release upload \
           --owner "BiTGApps" \
           --repo "BiTGApps-Package" \
           --token "$TOKEN" \
           --tag "${RELEASE}" \
           --release-name "BiTGApps ${RELEASE}" \
           "out/Assistant-v1.3.zip" \
           "out/AndroidAuto-v1.3.zip" \
           "out/Markup-v1.3.zip"

       - name: Upload Build Artifact
         uses: actions/upload-artifact@v2
         with:
           name: BiTGApps-Build
           path: |
             out/Assistant-v1.3.zip
             out/AndroidAuto-v1.3.zip
             out/Markup-v1.3.zip
